Agriculture/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^agriculture_app/', include('agriculture_app.urls',namespace='agriculture')),
]

agriculture_app/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^home/$', views.home_function),
    url(r'^article/(?P<page_id>[0-9]+)$', views.article, name='article_page'),
    #url(r'^article/(?P<page_id>[0-9]+)$', views.article, name='article_page'),

    #url(r'^edit/(?P<page_id>[0-9]+)$', views.edit_page,name='edit_page'),
    url(r'^edit/(?P<page_id>[0-9]+)$', views.edit_page,name='edit_page'),
    url(r'^edit/action$', views.edit_action,name='edit_action'),

    url(r'^register/$', views.register,name='register_page'),
    url(r'^register/response$', views.register_response, name='register_response'),

    url(r'^login/$', views.login, name='login_page'),
]

agriculture_app/models.py
# Create your models here. 一个model对应数据库一张数据表
from django.db import models
from mongoengine import *
from datetime import datetime

# 连接数据库
connect('Data')  # 连接本地blog数据库
#connect('Data',host='127.0.0.1',port='27017')

# 如需验证和指定主机名
# connect('blog', host='192.168.3.1', username='root', password='1234')

class user(Document):
    userId = IntField(required=True)
    # id = ObjectIdField(primary_key=True,required=True)
    user = StringField(max_length=1000, required=True)
    password = StringField(max_length=1000, required=True)


class main_data(Document):

    ' 继承Document类,为普通文档 '
    myId = IntField( required=True)
    #id = ObjectIdField(primary_key=True,required=True)
    title = StringField(max_length=1000, required=True)
    content = StringField(max_length=1000, required=True)



'''
class Main_data(models.Model):
    title = models.CharField(max_length=32,default='Title')
    content = models.TextField(null=True)
    create_time = models.DateTimeField(null=True) #创建对象的时添加当前时间

    def __str__(self):  #解决后台（admin）管理中只显示 Article object 这样一个对象
        return self.title

'''

agriculture_app/views.py
from django.db import models
from django.shortcuts import render

# Create your views here.
from agriculture_app.models import main_data


def home_function(request):
    articles = main_data.objects.all()
    return render(request,'home_.html',{'articles':articles})

def article(request,page_id):
    articles = main_data.objects.get(myId=str(page_id))  #和url中的 page_id  名字一样
    return render(request, 'article.html', {'articles': articles})

def edit_page(request,page_id):
    if str(page_id) == '0': #数据库中id 从1开始的
        return render(request, 'edit_page.html')
    articles = main_data.objects.get(myId=str(page_id))
    return render(request, 'edit_page.html', {'articles': articles})
def edit_action(request):
    title = request.POST.get('title','TITLE')
    content = request.POST.get('content','CONTENT')
    article_id = request.POST.get('article_id','0')
    if article_id == '0':
        main_data.objects.create(myId=5,title=title, content=content)  # 存到数据库
        # 返回到主页
        articles = main_data.objects.all()
        return render(request, 'home_.html', {'articles': articles})
    else:
        articles = main_data.objects.get(myId=str(article_id))
        articles.title = title
        articles.content = content
        articles.save()
        return render(request, 'article.html', {'articles': articles})

def myId():

    return 5


def register(request):
    return render(request,'register.html')
def register_response(request):
    title = request.POST.get('title','TITLE')
    content = request.POST.get('content','CONTENT')
    main_data.objects.create(title=title, content=content)  #存到数据库

    #返回到主页
    articles = main_data.objects.all()
    return render(request, 'home_.html', {'articles': articles})

def login(request):
    articles = main_data.objects.all()
    return render(request, 'login.html',{'articles':articles})
def login_response(request):

    # 返回到主页
    articles = main_data.objects.all()
    return render(request, 'home_.html', {'articles': articles})

agriculture_app/templates/article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文章界面</title>
</head>
<body>
<h1>{{ articles.title }}</h1>
<h1>{{ articles.content }}</h1>
<a href="{% url 'agriculture:edit_page' articles.myId %}">修改文章</a>
</body>
</html>

agriculture_app/templates/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑文章</title>
</head>
<body>
<form action="{% url 'agriculture:edit_action' %}" method="post"> <!-- 表单提交的目的url 服务器通过url请求数据执行操作-->
    {% csrf_token %}<!--post 请求的都要加上面一句 避免403错误-->
    <input type="hidden" name="article_id" value="{{ articles.myId | default:'0' }}"/>
    <!-- 表单提交 action 所用 （templates下）过滤器default（可叠加）-->
    <label>文章标题
        <input type="text" name="title" value="{{ articles.title }}"/>
    </label>
    <br/>
    <label>文章内容
        <input type="text" name="content" value="{{ articles.content }}"/>
    </label>
    <br/>
    <input type="submit" value="提交"/>
</form>
</body>
</html>

<!--{% if articles %}
        <input type="hidden" name="article_id" value="{{ articles.id }}"/> <!-- 表单提交 action 所用--
        <label>文章标题
            <input type="text" name="title" value="{{ articles.title }}"/>
        </label>
        <br/>
        <label>文章内容
            <input type="text" name="content" value="{{ articles.content }}"/>
        </label>
        <br/>
    {% else %}
        <input type="hidden" name="article_id" value="0"/>
        <label>文章标题
            <input type="text" name="title"/>
        </label>
        <br/>
        <label>文章内容
            <input type="text" name="content"/>
        </label>
        <br/>
    {% endif %}  -->

agriculture_app/templates/home_.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
<a href="{% url 'agriculture:register_page' %}">注册</a>

<a href="{% url 'agriculture:login_page' %}">登陆</a>
<br/>

<a href="{% url 'agriculture:edit_page' 0 %}">添加文章</a>
<br/>
{% for article in articles %}
    <a href="{% url 'agriculture:article_page' article.myId %}">{{ article.title }}</a>
    <br/>
{% endfor %}

</body>
</html>

agriculture_app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登陆</title>
</head>
<body>
<form action="" method="post">  <!-- 表单提交的目的url-->
    {% csrf_token %}<!--post 请求的都要加上面一句 避免403错误-->
    <label>文章标题
        <input type="text" name="title"/>
    </label>
    <br/>
    <label>文章内容
        <input type="text" name="content"/>
    </label>
    <br/>
    <input type="submit" value="登陆"/>
</form>
</body>
</html>

agriculture_app/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册界面</title>
</head>
<body>
<form action="{% url 'agriculture:register_response' %}" method="post"> <!-- 表单提交的目的url-->
    {% csrf_token %}<!--post 请求的都要加上面一句 避免403错误-->
    <label>文章标题
        <input type="text" name="title"/>
    </label>
    <br/>
    <label>文章内容
        <input type="text" name="content"/>
    </label>
    <br/>
    <input type="submit" value="提交"/>
</form>
</body>
</html>